[agent]
agent = "exhaustive"
nranks = 36

[engine]
engine = "twozone-engine"
fuel = "dodecane"
rxnmech = "dodecane_lu_nox.cti"
observables = ['ca', 'p', 'T', 'success_ninj', 'can_inject']
nsteps = 101
ename = "Isooctane_MBT_DI_50C_Summ.xlsx"
max_minj = 2.2e-5
mdot = 0.05
