# Configuring:
# install miniconda
# conda env create -f environment.yaml
name: MPRL
channels: !!python/tuple
  - defaults
  - cantera
  - conda-forge
dependencies:
  - cantera
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - tensorflow-gpu
  - xlrd
  - pip:
      - mpi4py --no-binary mpi4py
      - atari-py==0.2.0
      - stable-baselines
      - parameter-sherpa
