# Configuring:
# install miniconda
# conda env create -f environment.yaml
name: MPRL
channels:
  - defaults
  - cantera
  - conda-forge
dependencies:
  - cantera
  - gitpython
  - ipython
  - matplotlib
  - nose
  - numpy
  - pandas
  - pip
  - scipy
  - tensorflow-cpu
  - tensorboard
  - toml
  - xlrd
  - pip:
      - -r requirements.txt
      - stable-baselines[mpi]
      - parameter-sherpa
