# Configuring:
# install miniconda
# conda env create -f environment.yaml
name: rl-combustion
channels: !!python/tuple
  - defaults
  - cantera
  - conda-forge
dependencies:
  - cantera
  - ipython
  - matplotlib
  - numpy
  - pandas
  - pip
  - scipy
  - xlrd
  - pip:
      - stable-baselines
