# Configuring:
# install miniconda
# conda env create -f environment.yaml
name: MPRL
channels:
  - defaults
  - cantera
  - conda-forge
dependencies:
  - cantera=2.4.0
  - gitpython=3.0.5
  - ipython=7.13.0
  - matplotlib=3.1.3
  - nose=1.3.7
  - numpy=1.15.4
  - pandas=1.0.1
  - pip=20.0.2
  - scipy=1.4.1
  - tensorflow=1.14
  - tensorboard=1.14.0
  - toml=0.10.0
  - xlrd=1.2.0
  - pip:
      - -r requirements.txt
      - stable-baselines==2.10.0
      - parameter-sherpa==1.0.6
