[agent]
agent = "ppo"
update_nepisodes = 20
number_episodes = 20000
pretrained_agent = "../../a/agent.zip"

[engine]
engine = "reactor-engine"
fuel = "dodecane"
rxnmech = "dodecane_lu_nox.cti"
observables = ['ca', 'p', 'T', 'success_ninj', 'can_inject']
nsteps = 101
ename = "Isooctane_MBT_DI_50C_Summ.xlsx"
mdot = 0.01
max_minj = 2.2e-5

[reward]
names = ["work", "nox"]
norms=[1.0, 1.0e-7]
weights = [0.0, 1.0]
negative_reward = -1000.0