[agent]
agent = "manual"
injection_cas = [-12, -10, -8, -6, -4]
qdot_cas = [-110, -108, -106, -104, -102, -100,  -98,  -96,  -94,  -92,  -90, -88,  -86,  -84,  -82,  -80,  -78,  -76,  -74,  -72,  -70,  -68, -66,  -64,  -62,  -60,  -58,  -56,  -54,  -52,  -50,  -48,  -46, -44,  -42,  -40,  -38,  -36,  -34,  -32,  -30,  -28,  -26,  -24, -22,  -20,  -18,  -16,  -14,  -12,  -10,   -8,   -6]

[engine]
engine = "reactor-engine"
fuel = "dodecane"
rxnmech = "dodecane_lu_nox.cti"
observables = ['ca', 'p', 'T', 'success_ninj', 'can_inject']
nsteps = 101
mdot = 0.02
max_minj = 5e-5
use_qdot = true
ename = "Isooctane_MBT_DI_50C_Summ.xlsx"