[agent]
agent = "ppo"
update_nepisodes = 10
number_episodes = 100

[engine]
engine = "reactor-engine"
fuel = 'dodecane'
rxnmech = "dodecane_lu_nox.cti"
observables = ['ca', 'p', 'T', 'success_ninj', 'can_inject']
nsteps = 101
mdot = 0.02
max_minj = 6.36e-05
max_pressure = 2000.0

[reward]
names = ["work", "nox"]
norms = [15.0, 0.01]
weights = [0.5, 0.5]
negative_reward = -10.0
randomize = false