[agent]
agent = "ppo"
update_nepisodes = 10
number_episodes = 60000

[engine]
engine = "reactor-engine"
fuel = 'dodecane'
rxnmech = "dodecane_lu_nox.cti"
observables = ['ca', 'p', 'T', 'success_ninj', 'can_inject']
nsteps = 101
mdot = 0.02
max_minj = 6.36e-05
max_pressure = 2000.0
