name: CI

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Cancel previous runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{github.token}}
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get install mpich libmpich-dev
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: lint
        auto-activate-base: false
      - run: |
          conda info
          conda list
          conda install -c conda-forge black
          black --check .
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: MPRL
        environment-file: env.yaml
        python-version: 3.7
        auto-activate-base: false
      - run: |
          conda info
          conda list

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.7
    # - name: Add conda to system path
    #   run: |
    #     echo $CONDA/bin >> $GITHUB_PATH
    #     conda init bash
    # - name: Lint with black
    #   shell: bash -l {0}
    #   run: |
    #     conda create -n lint -c conda-forge python=3.8 black
    #     conda activate lint
    #     black --check .
    #     conda deactivate
    #     conda remove --name lint --all
    # - name: Install dependencies
    #   shell: bash -l {0}
    #   run: |
    #     sudo apt-get install mpich libmpich-dev
    #     conda env update --file env.yaml --name MPRL
    # - name: Test with nose
    #   shell: bash -l {0}
    #   run: |
    #     conda activate MPRL
    #     nosetests
    #     conda deactivate
